name: Build-T4
  
on:  
  workflow_dispatch:  
    inputs:  
      BOARD:  
        description: 'Board type'  
        required: true 
        default: 'nanopct4'
        type: choice
        options:
          - 'nanopct4'
      BRANCH:  
        description: 'Armbian branch'  
        default: 'edge'  
        required: true 
        type: choice 
        options:
          - 'current'
          - 'edge'
      RELEASE:  
        description: 'Release name' 
        default: 'bookworm'
        required: true  
        type: choice
        options:
          - 'jammy'
          - 'noble'
          - 'bookworm'
          - 'trixie'
      Version:
        description: 'Armbian Version'
        default: 'main'
        required: true 
        type: choice
        options: 
          - 'main' 
          - 'v24.11'
      BUILD_DESKTOP:  
        description: 'Build desktop environment'  
        default: 'no'  
        required: false  
        type: choice
        options:
          - 'yes'
          - 'no'
      BUILD_MINIMAL:  
        description: 'BUILD MINIMAL environment'  
        default: 'yes'  
        required: false  
        type: choice
        options:
          - 'yes'
          - 'no'
      PREFER_DOCKER:
        description: 'Use Docker build'
        default: 'no'
        required: false
        type: choice
        options:
          - 'yes'
          - 'no'
      DOCKER_ARMBIAN_BASE_IMAGE:
        description: 'Docker IMAGE'
        default: 'ubuntu:jammy'
        required: false
        type: choice
        options:
          - 'ubuntu:jammy'
          - 'ubuntu:noble'
          - 'debian:bookworm'        

env:
  TZ: Asia/Shanghai
  
jobs:  
  build-armbian-t4:  
    runs-on: ubuntu-24.04  
    steps:  
      - name: Checkout  
        uses: actions/checkout@v4  
          
      - name: Initialization environment
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker_images_ids=$(docker images -q)
          if [ -n "$docker_images_ids" ]; then
            docker rmi $docker_images_ids
          fi
          docker image prune -a -f
          sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* openjdk* mysql* php* mongodb* dotnet* moby* snapd* android* || true
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo timedatectl set-timezone "${TZ}"
          sudo mkdir -p /mnt/workdir
          sudo chown $USER:$GROUPS /mnt/workdir
          df -Th
  
      - name: Download source code
        working-directory: /mnt/workdir
        run: |
          df -hT ${PWD}
          git clone -q --single-branch --depth=1 --branch=${{ inputs.Version }} https://github.com/armbian/build.git build 
          ln -sf /mnt/workdir/build $GITHUB_WORKSPACE/build

          cd build/
          cp -f ${{ github.workspace }}/patch/config/* config/kernel/
          cp -f ${{ github.workspace }}/patch/fixdeb/* lib/functions/compilation/
          cp -f ${{ github.workspace }}/patch/fiximg/* lib/functions/configuration/
          cp -f ${{ github.workspace }}/patch/sbin/* packages/bsp/common/usr/sbin/
          cp -f ${{ github.workspace }}/patch/VERSION ./
          rm -f patch/kernel/archive/rockchip64-6.12/rk3399-fix-pci-phy.patch
          rm -f patch/kernel/archive/rockchip64-6.6/rk3399-fix-pci-phy.patch
          cp -f ${{ github.workspace }}/patch/T4/fix-CPU-information.patch patch/kernel/archive/rockchip64-6.12/
          cp -f ${{ github.workspace }}/patch/T4/fix-CPU-information.patch patch/kernel/archive/rockchip64-6.6/
          cp -f ${{ github.workspace }}/patch/T4/rk3399-t4-1.8-2.2-6.12.patch patch/kernel/archive/rockchip64-6.12/
          cp -f ${{ github.workspace }}/patch/T4/rk3399-t4-1.8-2.2.patch patch/kernel/archive/rockchip64-6.6/
          cp -f ${{ github.workspace }}/patch/T4/rockchip64_common.inc config/sources/families/include/
          ls -la
  
      - name: Compile Armbian [ ${{ inputs.BOARD }} ${{ inputs.BRANCH }} ${{ inputs.RELEASE }} ] 
        run: |  
          cd /mnt/workdir/build/ 
          ./compile.sh build BOARD=${{ inputs.BOARD }} BRANCH=${{ inputs.BRANCH }} RELEASE=${{ inputs.RELEASE }} BUILD_MINIMAL=${{ inputs.BUILD_MINIMAL }} BUILD_DESKTOP=${{ inputs.BUILD_DESKTOP }} \
            PREFER_DOCKER=${{ inputs.PREFER_DOCKER }} DOCKER_ARMBIAN_BASE_IMAGE=${{ inputs.DOCKER_ARMBIAN_BASE_IMAGE }} COMPRESS_OUTPUTIMAGE=xz KERNEL_CONFIGURE=no DEB_COMPRESS=xz
          
      - name: Set current year and month  
        run: |  
          echo "CURRENT_YEAR_MONTH=$(date +'%Y%m')" >> $GITHUB_ENV  

      - name: Prepare Release Metadata
        run: |   
          latest_image=$(ls ${{ github.workspace }}/build/output/images/Armbian_*.img.xz 2>/dev/null | sort -V | tail -n 1)
          
          if [ -z "$latest_image" ]; then
            echo "No image files found."
            exit 1
          fi
          
          VERSION=$(echo "$latest_image" | cut -d '_' -f 2)    
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Extracted VERSION: $VERSION"
        
      - name: Upload image to Release  
        if: success() 
        uses: ncipollo/release-action@main
        with:  
          tag: "Armbian-${{ inputs.RELEASE }}-${{ env.CURRENT_YEAR_MONTH }}-${{ inputs.BOARD }}"  
          name: "Armbian-${{ inputs.RELEASE }}-${{ env.CURRENT_YEAR_MONTH }}-${{ inputs.BOARD }}"  
          artifacts: "${{ github.workspace }}/build/output/images/*"
          allowUpdates: true
          removeArtifacts: false 
          replacesArtifacts: true 
          token: ${{ secrets.GH_TOKEN }}  
          body: |  
            ### Armbian Image Information  
            - Board: ${{ inputs.BOARD }}
            - Release: ${{ inputs.RELEASE }}    
            - Version: ${{ env.VERSION }}     
          draft: false  
          prerelease: false  
          
      - name: Prepare Kernel  
        run: |  
          cd "${GITHUB_WORKSPACE}/build/output/debs/"
          file=$(find . -maxdepth 1 -type f -name 'linux-image-*.deb' | head -n 1)  
    
          if [ -n "$file" ]; then  
            echo "Found file: $file"  
            KERNEL_VERSION=$(echo "$file" | cut -d '_' -f 5 | cut -d '-' -f 1)
            echo "KERNEL_VERSION=$KERNEL_VERSION" >> $GITHUB_ENV
            echo "Extracted KERNEL_VERSION: $KERNEL_VERSION"
          else
            echo "No matching file found. Available files are:"
            ls -1 "${GITHUB_WORKSPACE}/build/output/debs/"
            exit 1
          fi
          
          matching_files_array=($(ls linux-dtb* linux-headers* linux-image* linux-libc* 2>/dev/null))
          
          if [ ${#matching_files_array[@]} -gt 0 ]; then
            tar -czf "../kernel-${KERNEL_VERSION}.tar.gz" "${matching_files_array[@]}"
            echo "Compressed matching files to kernel-${KERNEL_VERSION}.tar.gz"
          else
            echo "No matching files found for compression."
            exit 1
          fi
          
          tar -tzf "../kernel-${KERNEL_VERSION}.tar.gz" || { echo "Failed to create valid tar.gz file"; exit 1; }
        
      - name: Upload Kernel Packages to Release  
        if: success()  
        uses: ncipollo/release-action@main  
        with:  
          tag: "Armbian-Kernel-${{ inputs.BOARD }}"
          name: "Armbian-Kernel-${{ inputs.BOARD }}"
          artifacts: "${{ github.workspace }}/build/output/kernel-${{ env.KERNEL_VERSION }}.tar.gz"  
          allowUpdates: true  
          removeArtifacts: false  
          replacesArtifacts: true  
          token: ${{ secrets.GH_TOKEN }}  
          body: |  
            ### Armbian Kernel Packages  
            - Usage method: After unzipping, install the deb packages in order
            - Packages include: linux-dtb | linux-headers | linux-image | linux-libc-dev
          draft: false  
          prerelease: false

      - name: Delete releases and workflows runs
        uses: ophub/delete-releases-workflows@main
        with:
          delete_releases: true
          releases_keep_latest: 10
          delete_workflows: true
          workflows_keep_day: 3
          gh_token: ${{ secrets.GH_TOKEN }}
